server:
  port: 8081

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:file:C:/Users/Admin/Desktop/spring/spring-kotlin-z/src/main/db
#                     E:/spring/kotlin-test-api/db
    username: campus
    password: campus
  jpa:
    hibernate:
      ddl-auto: 'update'

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
